# This file installs packages and declares associated capabilities
# For each defined package,
# - it transfers the package to the host
# - it runs a specific installation script
# - it declares the associated capabilities, if any
# - it does not cleans up the file. The file is in /tmp, so it should be safe
#   to keep it there to accelerate further transfers


- name: '[PYTHON3] Checking that required variables are set'
  fail:
    msg: "{{ item }} is not defined"
  when: item is undefined
  with_items:
    - python3_version
    - python3_installer

- name: "[PYTHON3] OSX installation tasks"
  include_tasks: install_python3_osx.yml
  when: ansible_distribution == 'MacOSX'

- name: "[PYTHON3] Ubuntu installation tasks"
  include_tasks: install_python3_ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: "[PYTHON3] Windows installation tasks"
  include_tasks: install_python3_windows.yml
  when: ansible_os_family == 'Windows'
